"""anthropic cache token columns

Revision ID: 90e81a2ab045
Revises: 49525b32cda7
Create Date: 2026-09-16 20:42:56.034846
"""
import sqlalchemy as sa

from alembic import op

revision = '90e81a2ab045'
down_revision = '49525b32cda7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_calls', sa.Column('cache_read_tokens', sa.Integer(), nullable=False))
    op.add_column('llm_calls', sa.Column('cache_write_tokens', sa.Integer(), nullable=False))
    op.drop_column('llm_calls', 'cached_input_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_calls', sa.Column('cached_input_tokens', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('llm_calls', 'cache_write_tokens')
    op.drop_column('llm_calls', 'cache_read_tokens')
    # ### end Alembic commands ###
